version: "3.9"
services:
  mysql_214:
    env_file:
      - .env
    image: mysql:latest
    user: "999:999"
    container_name: mysql_214
    hostname: mysql_214
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./mysql_214:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: America/Sao_Paulo
